feeds:
  - name: "DaringFireball"
    url: "https://daringfireball.net/feeds/main"
  - name: "pgessays"
    url: "http://www.aaronsw.com/2002/feeds/pgessays.rss"
  - name: "SimonWillison"
    url: "https://simonwillison.net/atom/everything/"
  - name: "marco"
    url: "https://marco.org/rss"
  - name: "dereksivers"
    url: "https://sive.rs/en.atom"
  - name: "kaushikgopal"
    url: "https://kau.sh/feed.xml"
  - name: "astralcodexten"
    url: "https://www.astralcodexten.com/feed"
  - name: "thinkingoutloud"
    url: "https://newsletter.jantegze.com/feed"
  - name: "AnthropicNews"
    url: "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_news.xml"
  - name: "appaddict"
    url: "https://apps.louplummer.lol/feed.atom"
  - name: "indieapp"
    url: "https://9to5mac.com/guides/indie-app-spotlight/feed/"
  - name: "macmenubar"
    url: "https://macmenubar.com/feed/"
  - name: "thriftmac"
    url: "https://feeds.feedburner.com/thriftmac"
  - name: "basicappleguy"
    url: "https://basicappleguy.com/basicappleblog?format=rss"
  # 按这个格式添加更多源
