feeds:
  - name: "DaringFireball"
    url: "https://daringfireball.net/feeds/main"
  - name: "pgessays"
    url: "http://www.aaronsw.com/2002/feeds/pgessays.rss"
  - name: "SimonWillisonQuotes"
    url: "https://simonwillison.net/atom/everything/"
    filter: "blockquote"
  - name: "marco"
    url: "https://marco.org/rss"
  - name: "dereksivers"
    url: "https://sive.rs/en.atom"
  - name: "kaushikgopal"
    url: "https://kau.sh/feed.xml"
  - name: "thinkingoutloud"
    url: "https://newsletter.jantegze.com/feed"
  - name: "AnthropicNews"
    url: "https://rsshub.bestblogs.dev/anthropic/news"
  - name: "appaddict"
    url: "https://apps.louplummer.lol/feed.atom"
  - name: "indieapp"
    url: "https://9to5mac.com/guides/indie-app-spotlight/feed/"
    fetch_full_content: true
  - name: "macmenubar"
    url: "https://macmenubar.com/feed/"
  - name: "basicappleguy"
    url: "https://basicappleguy.com/basicappleblog?format=rss"
  - name: "workspaces"
    url: "https://rss.beehiiv.com/feeds/A7QnI2IsJ7.xml"
    fetch_full_content: true
  - name: "dianying4k"
    url: "rsshub://telegram/channel/dianying4K"
    translate: false
  - name: "v2ex-hot"
    url: "rsshub://v2ex/topics/hot"
    fetch_full_content: true
    translate: false
  - name: "mac52ipod"
    url: "http://www.mac52ipod.cn/feed.php"
    fetch_full_content: true
    translate: false
  - name: "landiannews"
    url: "https://www.landiannews.com/feed"
    fetch_full_content: true
    translate: false
  - name: "36kr-hot"
    url: "rsshub://36kr/hot-list"
    fetch_full_content: true
    translate: false
  - name: "nicenews"
    url: "https://nicenews.com/feed/"
    fetch_full_content: true
  - name: "franzgraf"
    url: "https://www.franzgraf.de/feed"
    fetch_full_content: true
  # 按这个格式添加更多源
